//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WorkCopyV1._0.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FitBourneDBV1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FitBourneDBV1Container object using the connection string found in the 'FitBourneDBV1Container' section of the application configuration file.
        /// </summary>
        public FitBourneDBV1Container() : base("name=FitBourneDBV1Container", "FitBourneDBV1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FitBourneDBV1Container object.
        /// </summary>
        public FitBourneDBV1Container(string connectionString) : base(connectionString, "FitBourneDBV1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FitBourneDBV1Container object.
        /// </summary>
        public FitBourneDBV1Container(EntityConnection connection) : base(connection, "FitBourneDBV1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
